default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 2

development:
  <<: *default

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
